global:
  user_agent: "RentalStatsBot/1.0 (+contact: you@example.com)"
  max_pages: 40
  page_sleep_sec: 1.5
  ad_sleep_sec: 0.8

  # Outliergrenser (kan justeres)
  min_price_nok: 2000
  max_price_nok: 100000
  min_sqm: 10
  max_sqm: 400

markets:
  - key: narvik_no
    country: NO
    city: "Narvik"
    currency: "NOK"
    source: "FINN"
    search_url: "https://www.finn.no/realestate/lettings/search.html?filters=&lat=68.437705&lon=17.424586&radius=3000"

  - key: tromso_no
    country: NO
    city: "Tromsø"
    currency: "NOK"
    source: "FINN"
    search_url: "https://www.finn.no/realestate/lettings/search.html?lat=69.6492&lon=18.9553&radius=6000"
